[env:matrixportal_m4]
platform = atmelsam
board = adafruit_matrix_portal_m4
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/adafruit/Adafruit_Protomatter.git
  adafruit/Adafruit GFX Library
  adafruit/Adafruit BusIO
  adafruit/Adafruit Zero DMA Library
lib_ignore =
  Adafruit TinyUSB Library
